inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
    - node_modules/**/*
    - vendor/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - db/schema.rb