AllCops:
  Exclude:
    - 'node_modules/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'