language: ruby
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
rvm:
  - 2.4.1
branches:
  only:
    - master
script:
  - RAILS_ENV=test bundle exec rubocop -c .rubocop.yml
  - RAILS_ENV=test bundle exec rake
before_script:
  - yarn install